//! doltclaw CLI (behind feature = "cli")

#[cfg(feature = "cli")]
use clap::{Parser, Subcommand};

#[cfg(feature = "cli")]
#[derive(Parser)]
#[command(name = "doltclaw", version, about = "Minimal agent runtime for dirmacs")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[cfg(feature = "cli")]
#[derive(Subcommand)]
enum Commands {
    /// Run a prompt through the agent
    Run {
        /// The prompt to execute
        prompt: String,
        /// Config file path
        #[arg(short, long, default_value = "doltclaw.toml")]
        config: String,
    },
    /// Validate configuration
    Check {
        /// Config file path
        #[arg(short, long, default_value = "doltclaw.toml")]
        config: String,
    },
    /// Migrate openclaw.json to doltclaw.toml
    Migrate {
        /// Path to openclaw.json
        path: String,
    },
}

#[cfg(feature = "cli")]
#[tokio::main]
async fn main() -> doltclaw::Result<()> {
    tracing_subscriber::fmt::init();
    let cli = Cli::parse();

    match cli.command {
        Commands::Run { prompt, config } => {
            let cfg = doltclaw::Config::load(config.as_ref())?;
            let mut agent = doltclaw::Agent::from_config(cfg)?;
            let response = agent.execute(&prompt).await?;
            println!("{}", response.content);
            eprintln!(
                "\n--- {} iterations, {} tokens, model: {} ---",
                response.iterations, response.usage.total_tokens, response.model_used
            );
        }
        Commands::Check { config } => {
            let cfg = doltclaw::Config::load(config.as_ref())?;
            println!("Config OK");
            for model_ref in cfg.model_chain() {
                let (provider, model) = cfg.resolve_model(model_ref)?;
                println!(
                    "  {} -> {} ({}k ctx, {}k max, reasoning={})",
                    model_ref,
                    model.name,
                    model.context_window / 1024,
                    model.max_tokens / 1024,
                    model.reasoning
                );
                println!("    API: {}", provider.base_url);
            }
        }
        Commands::Migrate { path } => {
            let json_str = std::fs::read_to_string(&path)
                .map_err(|e| doltclaw::Error::Io(e))?;
            let json: serde_json::Value = serde_json::from_str(&json_str)
                .map_err(|e| doltclaw::Error::Config(format!("Invalid JSON: {}", e)))?;
            let toml = migrate_openclaw_json(&json);
            print!("{}", toml);
        }
    }

    Ok(())
}

#[cfg(feature = "cli")]
fn migrate_openclaw_json(json: &serde_json::Value) -> String {
    let mut out = String::new();
    out.push_str("# Generated by: doltclaw migrate\n\n");

    // Providers
    if let Some(providers) = json.pointer("/models/providers") {
        if let Some(obj) = providers.as_object() {
            for (name, provider) in obj {
                out.push_str(&format!("[providers.{}]\n", name));
                if let Some(url) = provider.get("baseUrl").and_then(|v| v.as_str()) {
                    out.push_str(&format!("base_url = \"{}\"\n", url));
                }
                if let Some(key) = provider.get("apiKey").and_then(|v| v.as_str()) {
                    out.push_str(&format!("api_key = \"{}\"\n", key));
                }
                if let Some(api) = provider.get("api").and_then(|v| v.as_str()) {
                    out.push_str(&format!("api = \"{}\"\n", api));
                }
                out.push('\n');

                if let Some(models) = provider.get("models").and_then(|v| v.as_array()) {
                    for model in models {
                        out.push_str(&format!("[[providers.{}.models]]\n", name));
                        if let Some(id) = model.get("id").and_then(|v| v.as_str()) {
                            out.push_str(&format!("id = \"{}\"\n", id));
                        }
                        if let Some(n) = model.get("name").and_then(|v| v.as_str()) {
                            out.push_str(&format!("name = \"{}\"\n", n));
                        }
                        if let Some(r) = model.get("reasoning").and_then(|v| v.as_bool()) {
                            out.push_str(&format!("reasoning = {}\n", r));
                        }
                        if let Some(cw) = model.get("contextWindow").and_then(|v| v.as_u64()) {
                            out.push_str(&format!("context_window = {}\n", cw));
                        }
                        if let Some(mt) = model.get("maxTokens").and_then(|v| v.as_u64()) {
                            out.push_str(&format!("max_tokens = {}\n", mt));
                        }
                        out.push('\n');
                    }
                }
            }
        }
    }

    // Agent
    out.push_str("[agent]\n");
    if let Some(primary) = json.pointer("/agents/defaults/model/primary").and_then(|v| v.as_str()) {
        out.push_str(&format!("primary = \"{}\"\n", primary));
    }
    if let Some(fallbacks) = json
        .pointer("/agents/defaults/model/fallbacks")
        .and_then(|v| v.as_array())
    {
        let fbs: Vec<String> = fallbacks
            .iter()
            .filter_map(|v| v.as_str().map(|s| format!("\"{}\"", s)))
            .collect();
        out.push_str(&format!("fallbacks = [{}]\n", fbs.join(", ")));
    }
    out.push('\n');

    out.push_str("[agent.params]\n");
    out.push_str("temperature = 1.0\n");
    out.push_str("top_p = 0.95\n");

    out
}

#[cfg(not(feature = "cli"))]
fn main() {
    eprintln!("doltclaw CLI requires the 'cli' feature. Build with: cargo build --features cli");
    std::process::exit(1);
}
